disabled_rules:
  - empty_enum_arguments        # It warns about an explicit pattern we use.
  - superfluous_disable_command # Disabled since we disable some rules pre-emptively to avoid issues in the future
  - todo                        # Disabled while we are filling out the framework; re-enable when we get closer to completion
  - nesting                     # Does not make sense anymore since Swift 4 uses nested `CodingKeys` enums for example
opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_end_indentation
  - closure_spacing
  - colon
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - notification_center_detachment
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - trailing_comma
  - trailing_whitespace
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - .build
  - build
  - Carthage
  - Other
  - Tools
  - Templates

attributes:
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
closure_spacing: error
empty_count: error
explicit_init: error
fatal_error_message: error
file_header:
  severity: error
  forbidden_pattern: |
                     \/\/
                     \/\/  .*?\..*
                     \/\/  .*
                     \/\/
                     \/\/  Created by .*? on .*\.
                     \/\/  Copyright © \d{4} .*\. All rights reserved\.
                     \/\/
implicit_getter: error
indentation: 4 # 4 spaces
line_length:
  warning: 200 # our line length is 120 chars, sometimes surpassing that is fine
  error: 200
  ignores_function_declarations: true
multiline_arguments:
  first_argument_location: next_line
number_separator:
  minimum_length: 5 # number of digits, i.e. >= 10_000
redundant_nil_coalescing: error
trailing_comma:
  mandatory_comma: true
vertical_whitespace:
  max_empty_lines: 2
weak_delegate: warning

reporter:
  - "xcode"
  - "junit"
