name: CI

on: pull_request

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: Tools/ci-xcode.sh
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  spm:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: Tools/ci-spm.sh
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.0.1
        with:
          args: lint --no-cache --strict
